# settings/scan_codes.py
import sdl2

class ScanCodes: 
    SCANCODE_UNKNOWN: int = sdl2.SDL_SCANCODE_UNKNOWN
    SCANCODE_A: int = sdl2.SDL_SCANCODE_A
    SCANCODE_B: int = sdl2.SDL_SCANCODE_B
    SCANCODE_C: int = sdl2.SDL_SCANCODE_C
    SCANCODE_D: int = sdl2.SDL_SCANCODE_D
    SCANCODE_E: int = sdl2.SDL_SCANCODE_E
    SCANCODE_F: int = sdl2.SDL_SCANCODE_F
    SCANCODE_G: int = sdl2.SDL_SCANCODE_G
    SCANCODE_H: int = sdl2.SDL_SCANCODE_H
    SCANCODE_I: int = sdl2.SDL_SCANCODE_I
    SCANCODE_J: int = sdl2.SDL_SCANCODE_J
    SCANCODE_K: int = sdl2.SDL_SCANCODE_K
    SCANCODE_L: int = sdl2.SDL_SCANCODE_L
    SCANCODE_M: int = sdl2.SDL_SCANCODE_M
    SCANCODE_N: int = sdl2.SDL_SCANCODE_N
    SCANCODE_O: int = sdl2.SDL_SCANCODE_O
    SCANCODE_P: int = sdl2.SDL_SCANCODE_P
    SCANCODE_Q: int = sdl2.SDL_SCANCODE_Q
    SCANCODE_R: int = sdl2.SDL_SCANCODE_R
    SCANCODE_S: int = sdl2.SDL_SCANCODE_S
    SCANCODE_T: int = sdl2.SDL_SCANCODE_T
    SCANCODE_U: int = sdl2.SDL_SCANCODE_U
    SCANCODE_V: int = sdl2.SDL_SCANCODE_V
    SCANCODE_W: int = sdl2.SDL_SCANCODE_W
    SCANCODE_X: int = sdl2.SDL_SCANCODE_X
    SCANCODE_Y: int = sdl2.SDL_SCANCODE_Y
    SCANCODE_Z: int = sdl2.SDL_SCANCODE_Z

    SCANCODE_1: int = sdl2.SDL_SCANCODE_1
    SCANCODE_2: int = sdl2.SDL_SCANCODE_2
    SCANCODE_3: int = sdl2.SDL_SCANCODE_3
    SCANCODE_4: int = sdl2.SDL_SCANCODE_4
    SCANCODE_5: int = sdl2.SDL_SCANCODE_5
    SCANCODE_6: int = sdl2.SDL_SCANCODE_6
    SCANCODE_7: int = sdl2.SDL_SCANCODE_7
    SCANCODE_8: int = sdl2.SDL_SCANCODE_8
    SCANCODE_9: int = sdl2.SDL_SCANCODE_9
    SCANCODE_0: int = sdl2.SDL_SCANCODE_0

    SCANCODE_RETURN: int = sdl2.SDL_SCANCODE_RETURN
    SCANCODE_ESCAPE: int = sdl2.SDL_SCANCODE_ESCAPE
    SCANCODE_BACKSPACE: int = sdl2.SDL_SCANCODE_BACKSPACE
    SCANCODE_TAB: int = sdl2.SDL_SCANCODE_TAB
    SCANCODE_SPACE: int = sdl2.SDL_SCANCODE_SPACE

    SCANCODE_MINUS: int = sdl2.SDL_SCANCODE_MINUS
    SCANCODE_EQUALS: int = sdl2.SDL_SCANCODE_EQUALS
    SCANCODE_LEFTBRACKET: int = sdl2.SDL_SCANCODE_LEFTBRACKET
    SCANCODE_RIGHTBRACKET: int = sdl2.SDL_SCANCODE_RIGHTBRACKET
    SCANCODE_BACKSLASH: int = sdl2.SDL_SCANCODE_BACKSLASH

    SCANCODE_NONUSHASH: int = sdl2.SDL_SCANCODE_NONUSHASH

    SCANCODE_SEMICOLON: int = sdl2.SDL_SCANCODE_SEMICOLON
    SCANCODE_APOSTROPHE: int = sdl2.SDL_SCANCODE_APOSTROPHE
    SCANCODE_GRAVE: int = sdl2.SDL_SCANCODE_GRAVE

    SCANCODE_COMMA: int = sdl2.SDL_SCANCODE_COMMA
    SCANCODE_PERIOD: int = sdl2.SDL_SCANCODE_PERIOD
    SCANCODE_SLASH: int = sdl2.SDL_SCANCODE_SLASH

    SCANCODE_CAPSLOCK: int = sdl2.SDL_SCANCODE_CAPSLOCK

    SCANCODE_F1: int = sdl2.SDL_SCANCODE_F1
    SCANCODE_F2: int = sdl2.SDL_SCANCODE_F2
    SCANCODE_F3: int = sdl2.SDL_SCANCODE_F3
    SCANCODE_F4: int = sdl2.SDL_SCANCODE_F4
    SCANCODE_F5: int = sdl2.SDL_SCANCODE_F5
    SCANCODE_F6: int = sdl2.SDL_SCANCODE_F6
    SCANCODE_F7: int = sdl2.SDL_SCANCODE_F7
    SCANCODE_F8: int = sdl2.SDL_SCANCODE_F8
    SCANCODE_F9: int = sdl2.SDL_SCANCODE_F9
    SCANCODE_F10: int = sdl2.SDL_SCANCODE_F10
    SCANCODE_F11: int = sdl2.SDL_SCANCODE_F11
    SCANCODE_F12: int = sdl2.SDL_SCANCODE_F12

    SCANCODE_PRINTSCREEN: int = sdl2.SDL_SCANCODE_PRINTSCREEN
    SCANCODE_SCROLLLOCK: int = sdl2.SDL_SCANCODE_SCROLLLOCK
    SCANCODE_PAUSE: int = sdl2.SDL_SCANCODE_PAUSE
    SCANCODE_INSERT: int = sdl2.SDL_SCANCODE_INSERT

    SCANCODE_HOME: int = sdl2.SDL_SCANCODE_HOME
    SCANCODE_PAGEUP: int = sdl2.SDL_SCANCODE_PAGEUP
    SCANCODE_DELETE: int = sdl2.SDL_SCANCODE_DELETE
    SCANCODE_END: int = sdl2.SDL_SCANCODE_END
    SCANCODE_PAGEDOWN: int = sdl2.SDL_SCANCODE_PAGEDOWN
    SCANCODE_RIGHT: int = sdl2.SDL_SCANCODE_RIGHT
    SCANCODE_LEFT: int = sdl2.SDL_SCANCODE_LEFT
    SCANCODE_DOWN: int = sdl2.SDL_SCANCODE_DOWN
    SCANCODE_UP: int = sdl2.SDL_SCANCODE_UP

    SCANCODE_NUMLOCKCLEAR: int = sdl2.SDL_SCANCODE_NUMLOCKCLEAR
    SCANCODE_KP_DIVIDE: int = sdl2.SDL_SCANCODE_KP_DIVIDE
    SCANCODE_KP_MULTIPLY: int = sdl2.SDL_SCANCODE_KP_MULTIPLY
    SCANCODE_KP_MINUS: int = sdl2.SDL_SCANCODE_KP_MINUS
    SCANCODE_KP_PLUS: int = sdl2.SDL_SCANCODE_KP_PLUS
    SCANCODE_KP_ENTER: int = sdl2.SDL_SCANCODE_KP_ENTER
    SCANCODE_KP_1: int = sdl2.SDL_SCANCODE_KP_1
    SCANCODE_KP_2: int = sdl2.SDL_SCANCODE_KP_2
    SCANCODE_KP_3: int = sdl2.SDL_SCANCODE_KP_3
    SCANCODE_KP_4: int = sdl2.SDL_SCANCODE_KP_4
    SCANCODE_KP_5: int = sdl2.SDL_SCANCODE_KP_5
    SCANCODE_KP_6: int = sdl2.SDL_SCANCODE_KP_6
    SCANCODE_KP_7: int = sdl2.SDL_SCANCODE_KP_7
    SCANCODE_KP_8: int = sdl2.SDL_SCANCODE_KP_8
    SCANCODE_KP_9: int = sdl2.SDL_SCANCODE_KP_9
    SCANCODE_KP_0: int = sdl2.SDL_SCANCODE_KP_0
    SCANCODE_KP_PERIOD: int = sdl2.SDL_SCANCODE_KP_PERIOD

    SCANCODE_NONUSBACKSLASH: int = sdl2.SDL_SCANCODE_NONUSBACKSLASH

    SCANCODE_APPLICATION: int = sdl2.SDL_SCANCODE_APPLICATION
    SCANCODE_POWER: int = sdl2.SDL_SCANCODE_POWER

    SCANCODE_KP_EQUALS: int = sdl2.SDL_SCANCODE_KP_EQUALS

    SCANCODE_F13: int = sdl2.SDL_SCANCODE_F13
    SCANCODE_F14: int = sdl2.SDL_SCANCODE_F14
    SCANCODE_F15: int = sdl2.SDL_SCANCODE_F15
    SCANCODE_F16: int = sdl2.SDL_SCANCODE_F16
    SCANCODE_F17: int = sdl2.SDL_SCANCODE_F17
    SCANCODE_F18: int = sdl2.SDL_SCANCODE_F18
    SCANCODE_F19: int = sdl2.SDL_SCANCODE_F19
    SCANCODE_F20: int = sdl2.SDL_SCANCODE_F20
    SCANCODE_F21: int = sdl2.SDL_SCANCODE_F21
    SCANCODE_F22: int = sdl2.SDL_SCANCODE_F22
    SCANCODE_F23: int = sdl2.SDL_SCANCODE_F23
    SCANCODE_F24: int = sdl2.SDL_SCANCODE_F24
    SCANCODE_EXECUTE: int = sdl2.SDL_SCANCODE_EXECUTE
    SCANCODE_HELP: int = sdl2.SDL_SCANCODE_HELP
    SCANCODE_MENU: int = sdl2.SDL_SCANCODE_MENU
    SCANCODE_SELECT: int = sdl2.SDL_SCANCODE_SELECT
    SCANCODE_STOP: int = sdl2.SDL_SCANCODE_STOP
    SCANCODE_AGAIN: int = sdl2.SDL_SCANCODE_AGAIN
    SCANCODE_UNDO: int = sdl2.SDL_SCANCODE_UNDO
    SCANCODE_CUT: int = sdl2.SDL_SCANCODE_CUT
    SCANCODE_COPY: int = sdl2.SDL_SCANCODE_COPY
    SCANCODE_PASTE: int = sdl2.SDL_SCANCODE_PASTE
    SCANCODE_FIND: int = sdl2.SDL_SCANCODE_FIND
    SCANCODE_MUTE: int = sdl2.SDL_SCANCODE_MUTE
    SCANCODE_VOLUMEUP: int = sdl2.SDL_SCANCODE_VOLUMEUP
    SCANCODE_VOLUMEDOWN: int = sdl2.SDL_SCANCODE_VOLUMEDOWN
    SCANCODE_KP_COMMA: int = sdl2.SDL_SCANCODE_KP_COMMA
    SCANCODE_KP_EQUALSAS400: int = sdl2.SDL_SCANCODE_KP_EQUALSAS400

    SCANCODE_INTERNATIONAL1: int = sdl2.SDL_SCANCODE_INTERNATIONAL1
    SCANCODE_INTERNATIONAL2: int = sdl2.SDL_SCANCODE_INTERNATIONAL2
    SCANCODE_INTERNATIONAL3: int = sdl2.SDL_SCANCODE_INTERNATIONAL3
    SCANCODE_INTERNATIONAL4: int = sdl2.SDL_SCANCODE_INTERNATIONAL4
    SCANCODE_INTERNATIONAL5: int = sdl2.SDL_SCANCODE_INTERNATIONAL5
    SCANCODE_INTERNATIONAL6: int = sdl2.SDL_SCANCODE_INTERNATIONAL6
    SCANCODE_INTERNATIONAL7: int = sdl2.SDL_SCANCODE_INTERNATIONAL7
    SCANCODE_INTERNATIONAL8: int = sdl2.SDL_SCANCODE_INTERNATIONAL8
    SCANCODE_INTERNATIONAL9: int = sdl2.SDL_SCANCODE_INTERNATIONAL9

    SCANCODE_LANG1: int = sdl2.SDL_SCANCODE_LANG1
    SCANCODE_LANG2: int = sdl2.SDL_SCANCODE_LANG2
    SCANCODE_LANG3: int = sdl2.SDL_SCANCODE_LANG3
    SCANCODE_LANG4: int = sdl2.SDL_SCANCODE_LANG4
    SCANCODE_LANG5: int = sdl2.SDL_SCANCODE_LANG5
    SCANCODE_LANG6: int = sdl2.SDL_SCANCODE_LANG6
    SCANCODE_LANG7: int = sdl2.SDL_SCANCODE_LANG7
    SCANCODE_LANG8: int = sdl2.SDL_SCANCODE_LANG8
    SCANCODE_LANG9: int = sdl2.SDL_SCANCODE_LANG9

    SCANCODE_ALTERASE: int = sdl2.SDL_SCANCODE_ALTERASE
    SCANCODE_SYSREQ: int = sdl2.SDL_SCANCODE_SYSREQ
    SCANCODE_CANCEL: int = sdl2.SDL_SCANCODE_CANCEL
    SCANCODE_CLEAR: int = sdl2.SDL_SCANCODE_CLEAR
    SCANCODE_PRIOR: int = sdl2.SDL_SCANCODE_PRIOR
    SCANCODE_RETURN2: int = sdl2.SDL_SCANCODE_RETURN2
    SCANCODE_SEPARATOR: int = sdl2.SDL_SCANCODE_SEPARATOR
    SCANCODE_OUT: int = sdl2.SDL_SCANCODE_OUT
    SCANCODE_OPER: int = sdl2.SDL_SCANCODE_OPER
    SCANCODE_CLEARAGAIN: int = sdl2.SDL_SCANCODE_CLEARAGAIN
    SCANCODE_CRSEL: int = sdl2.SDL_SCANCODE_CRSEL
    SCANCODE_EXSEL: int = sdl2.SDL_SCANCODE_EXSEL

    SCANCODE_KP_00: int = sdl2.SDL_SCANCODE_KP_00
    SCANCODE_KP_000: int = sdl2.SDL_SCANCODE_KP_000
    SCANCODE_THOUSANDSSEPARATOR: int = sdl2.SDL_SCANCODE_THOUSANDSSEPARATOR
    SCANCODE_DECIMALSEPARATOR: int = sdl2.SDL_SCANCODE_DECIMALSEPARATOR
    SCANCODE_CURRENCYUNIT: int = sdl2.SDL_SCANCODE_CURRENCYUNIT
    SCANCODE_CURRENCYSUBUNIT: int = sdl2.SDL_SCANCODE_CURRENCYSUBUNIT
    SCANCODE_KP_LEFTPAREN: int = sdl2.SDL_SCANCODE_KP_LEFTPAREN
    SCANCODE_KP_RIGHTPAREN: int = sdl2.SDL_SCANCODE_KP_RIGHTPAREN
    SCANCODE_KP_LEFTBRACE: int = sdl2.SDL_SCANCODE_KP_LEFTBRACE
    SCANCODE_KP_RIGHTBRACE: int = sdl2.SDL_SCANCODE_KP_RIGHTBRACE
    SCANCODE_KP_TAB: int = sdl2.SDL_SCANCODE_KP_TAB
    SCANCODE_KP_BACKSPACE: int = sdl2.SDL_SCANCODE_KP_BACKSPACE
    SCANCODE_KP_A: int = sdl2.SDL_SCANCODE_KP_A
    SCANCODE_KP_B: int = sdl2.SDL_SCANCODE_KP_B
    SCANCODE_KP_C: int = sdl2.SDL_SCANCODE_KP_C
    SCANCODE_KP_D: int = sdl2.SDL_SCANCODE_KP_D
    SCANCODE_KP_E: int = sdl2.SDL_SCANCODE_KP_E
    SCANCODE_KP_F: int = sdl2.SDL_SCANCODE_KP_F
    SCANCODE_KP_XOR: int = sdl2.SDL_SCANCODE_KP_XOR
    SCANCODE_KP_POWER: int = sdl2.SDL_SCANCODE_KP_POWER
    SCANCODE_KP_PERCENT: int = sdl2.SDL_SCANCODE_KP_PERCENT
    SCANCODE_KP_LESS: int = sdl2.SDL_SCANCODE_KP_LESS
    SCANCODE_KP_GREATER: int = sdl2.SDL_SCANCODE_KP_GREATER
    SCANCODE_KP_AMPERSAND: int = sdl2.SDL_SCANCODE_KP_AMPERSAND
    SCANCODE_KP_DBLAMPERSAND: int = sdl2.SDL_SCANCODE_KP_DBLAMPERSAND
    SCANCODE_KP_VERTICALBAR: int = sdl2.SDL_SCANCODE_KP_VERTICALBAR
    SCANCODE_KP_DBLVERTICALBAR: int = sdl2.SDL_SCANCODE_KP_DBLVERTICALBAR
    SCANCODE_KP_COLON: int = sdl2.SDL_SCANCODE_KP_COLON
    SCANCODE_KP_HASH: int = sdl2.SDL_SCANCODE_KP_HASH
    SCANCODE_KP_SPACE: int = sdl2.SDL_SCANCODE_KP_SPACE
    SCANCODE_KP_AT: int = sdl2.SDL_SCANCODE_KP_AT
    SCANCODE_KP_EXCLAM: int = sdl2.SDL_SCANCODE_KP_EXCLAM
    SCANCODE_KP_MEMSTORE: int = sdl2.SDL_SCANCODE_KP_MEMSTORE
    SCANCODE_KP_MEMRECALL: int = sdl2.SDL_SCANCODE_KP_MEMRECALL
    SCANCODE_KP_MEMCLEAR: int = sdl2.SDL_SCANCODE_KP_MEMCLEAR
    SCANCODE_KP_MEMADD: int = sdl2.SDL_SCANCODE_KP_MEMADD
    SCANCODE_KP_MEMSUBTRACT: int = sdl2.SDL_SCANCODE_KP_MEMSUBTRACT
    SCANCODE_KP_MEMMULTIPLY: int = sdl2.SDL_SCANCODE_KP_MEMMULTIPLY
    SCANCODE_KP_MEMDIVIDE: int = sdl2.SDL_SCANCODE_KP_MEMDIVIDE
    SCANCODE_KP_PLUSMINUS: int = sdl2.SDL_SCANCODE_KP_PLUSMINUS
    SCANCODE_KP_CLEAR: int = sdl2.SDL_SCANCODE_KP_CLEAR
    SCANCODE_KP_CLEARENTRY: int = sdl2.SDL_SCANCODE_KP_CLEARENTRY
    SCANCODE_KP_BINARY: int = sdl2.SDL_SCANCODE_KP_BINARY
    SCANCODE_KP_OCTAL: int = sdl2.SDL_SCANCODE_KP_OCTAL
    SCANCODE_KP_DECIMAL: int = sdl2.SDL_SCANCODE_KP_DECIMAL
    SCANCODE_KP_HEXADECIMAL: int = sdl2.SDL_SCANCODE_KP_HEXADECIMAL

    SCANCODE_LCTRL: int = sdl2.SDL_SCANCODE_LCTRL
    SCANCODE_LSHIFT: int = sdl2.SDL_SCANCODE_LSHIFT
    SCANCODE_LALT: int = sdl2.SDL_SCANCODE_LALT
    SCANCODE_LGUI: int = sdl2.SDL_SCANCODE_LGUI
    SCANCODE_RCTRL: int = sdl2.SDL_SCANCODE_RCTRL
    SCANCODE_RSHIFT: int = sdl2.SDL_SCANCODE_RSHIFT
    SCANCODE_RALT: int = sdl2.SDL_SCANCODE_RALT
    SCANCODE_RGUI: int = sdl2.SDL_SCANCODE_RGUI

    SCANCODE_MODE: int = sdl2.SDL_SCANCODE_MODE

    SCANCODE_AUDIONEXT: int = sdl2.SDL_SCANCODE_AUDIONEXT
    SCANCODE_AUDIOPREV: int = sdl2.SDL_SCANCODE_AUDIOPREV
    SCANCODE_AUDIOSTOP: int = sdl2.SDL_SCANCODE_AUDIOSTOP
    SCANCODE_AUDIOPLAY: int = sdl2.SDL_SCANCODE_AUDIOPLAY
    SCANCODE_AUDIOMUTE: int = sdl2.SDL_SCANCODE_AUDIOMUTE
    SCANCODE_MEDIASELECT: int = sdl2.SDL_SCANCODE_MEDIASELECT
    SCANCODE_WWW: int = sdl2.SDL_SCANCODE_WWW
    SCANCODE_MAIL: int = sdl2.SDL_SCANCODE_MAIL
    SCANCODE_CALCULATOR: int = sdl2.SDL_SCANCODE_CALCULATOR
    SCANCODE_COMPUTER: int = sdl2.SDL_SCANCODE_COMPUTER
    SCANCODE_AC_SEARCH: int = sdl2.SDL_SCANCODE_AC_SEARCH
    SCANCODE_AC_HOME: int = sdl2.SDL_SCANCODE_AC_HOME
    SCANCODE_AC_BACK: int = sdl2.SDL_SCANCODE_AC_BACK
    SCANCODE_AC_FORWARD: int = sdl2.SDL_SCANCODE_AC_FORWARD
    SCANCODE_AC_STOP: int = sdl2.SDL_SCANCODE_AC_STOP
    SCANCODE_AC_REFRESH: int = sdl2.SDL_SCANCODE_AC_REFRESH
    SCANCODE_AC_BOOKMARKS: int = sdl2.SDL_SCANCODE_AC_BOOKMARKS
    SCANCODE_BRIGHTNESSDOWN: int = sdl2.SDL_SCANCODE_BRIGHTNESSDOWN
    SCANCODE_BRIGHTNESSUP: int = sdl2.SDL_SCANCODE_BRIGHTNESSUP
    SCANCODE_DISPLAYSWITCH: int = sdl2.SDL_SCANCODE_DISPLAYSWITCH
    SCANCODE_KBDILLUMTOGGLE: int = sdl2.SDL_SCANCODE_KBDILLUMTOGGLE
    SCANCODE_KBDILLUMDOWN: int = sdl2.SDL_SCANCODE_KBDILLUMDOWN
    SCANCODE_KBDILLUMUP: int = sdl2.SDL_SCANCODE_KBDILLUMUP
    SCANCODE_EJECT: int = sdl2.SDL_SCANCODE_EJECT
    SCANCODE_SLEEP: int = sdl2.SDL_SCANCODE_SLEEP

    SCANCODE_APP1: int = sdl2.SDL_SCANCODE_APP1
    SCANCODE_APP2: int = sdl2.SDL_SCANCODE_APP2
    SCANCODE_AUDIOREWIND: int = sdl2.SDL_SCANCODE_AUDIOREWIND
    SCANCODE_AUDIOFASTFORWARD: int = sdl2.SDL_SCANCODE_AUDIOFASTFORWARD

    SCANCODE_SOFTLEFT: int = sdl2.SDL_SCANCODE_SOFTLEFT
    SCANCODE_SOFTRIGHT: int = sdl2.SDL_SCANCODE_SOFTRIGHT
    SCANCODE_CALL: int = sdl2.SDL_SCANCODE_CALL
    SCANCODE_ENDCALL: int = sdl2.SDL_SCANCODE_ENDCALL

    NUM_SCANCODES: int = sdl2.SDL_NUM_SCANCODES