import sdl2

class EventTypes:
    EVENT_QUIT: int = sdl2.SDL_QUIT
    EVENT_KEYDOWN: int = sdl2.SDL_KEYDOWN
    EVENT_KEYUP: int = sdl2.SDL_KEYUP
    EVENT_MOUSEBUTTONDOWN: int = sdl2.SDL_MOUSEBUTTONDOWN
    EVENT_MOUSEBUTTONUP: int = sdl2.SDL_MOUSEBUTTONUP
    EVENT_MOUSEMOTION: int = sdl2.SDL_MOUSEMOTION
    EVENT_FIRST: int = sdl2.SDL_FIRSTEVENT
    EVENT_LAST: int = sdl2.SDL_LASTEVENT
    EVENT_ANY: int = 9999